### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by paulhollmann** [lennycolton/VATGlasses-Data-old#47]
Hi, this is no bug,
but it would be great if can provide how the files are structured.
I wanted to add the German Firs but I'm not quite sure if I got the formats right.
Thanks a lot...

**Comment by lennycolton** [comment]
Hi,

Information on the structure of each line in all files can be found in the Wiki.

Information on what to remove from your .sct/.ese files before running the parser can be found in the readme for the parsers branch.

If there's anything specific that you're not sure about the layout of, please feel free to ask.

I hope this helps.

**Comment by paulhollmann** [comment]
ah ok didn't see that ok makes much more sense now thanks
